workflows:
  version: 1.0
  build:
    name: Create New Release
    scripts:
      # Checkout code from the repository
      - name: Checkout 
        script: |
          git clone https://github.com/Backdoor-v5/Backdoor-v5.git
          cd Backdoor-v5

      # Install dependencies
      - name: Install Dependencies
        script: |
          curl -LO https://github.com/ProcursusTeam/ldid/releases/download/v2.1.5-procursus7/ldid_macosx_x86_64
          sudo install -m755 ldid_macosx_x86_64 /usr/local/bin/ldid
          brew install 7zip gnu-sed

      # Compile the package
      - name: Compile
        script: |
          mkdir upload
          make package SCHEME="'backdoor (Release)'" CFLAGS="-Onone"
          mv packages/* upload/

      # Get Version Number
      - name: Get Version Number
        script: |
          VERSION=$( /usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" Payload/backdoor.app/Info.plist )
          echo "VERSION=${VERSION}" > version.txt

      # Setup the files for release
      - name: Setup
        script: |
          source version.txt
          mv upload/backdoor.ipa upload/backdoor_v${VERSION}.ipa
          cp upload/backdoor_v${VERSION}.ipa upload/backdoor_v${VERSION}.tipa

      # Create GitHub Release
      - name: Create GitHub Release
        script: |
          VERSION=$(cat version.txt | cut -d'=' -f2)
          gh release create "v${VERSION}" upload/*ipa --title "backdoor v${VERSION}" --notes "Automatically generated release"

    environment:
      COMPOSER_CACHE: true
      NODE_VERSION: '14'
      # Add any other environment variables you require here

    # You might need these if you are using protect branch and want to run builds
    # triggers:
    #   on_build_trigger: active