workflows:
  create-new-release:
    name: Create New Release
    instance_type: mac_mini_m1  # Adjust based on available Codemagic instances
    environment:
      vars:
        SCHEME: "'backdoor (Release)'"
        CFLAGS: "-Onone"
      groups:
        - github_credentials  # Add GITHUB_TOKEN in Codemagic UI environment group
    scripts:
      - name: Checkout
        script: |
          # Codemagic automatically checks out the repo, no need to git clone
          # Just ensure we're in the right directory
          cd $CM_BUILD_DIR

      - name: Install Dependencies
        script: |
          curl -LO https://github.com/ProcursusTeam/ldid/releases/download/v2.1.5-procursus7/ldid_macosx_x86_64
          sudo install -m755 ldid_macosx_x86_64 /usr/local/bin/ldid
          brew install 7zip gnu-sed

      - name: Compile
        script: |
          mkdir upload
          make package SCHEME="$SCHEME" CFLAGS="$CFLAGS"
          mv packages/* upload/

      - name: Get Version Number
        script: |
          VERSION=$( /usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" Payload/backdoor.app/Info.plist )
          echo "export VERSION=$VERSION" >> $CM_ENV

      - name: Setup
        script: |
          mv upload/backdoor.ipa upload/backdoor_v${VERSION}.ipa
          cp upload/backdoor_v${VERSION}.ipa upload/backdoor_v${VERSION}.tipa

    publishing:
      github:
        tag: v${VERSION}
        release_notes: automatic
        artifacts:
          - upload/*ipa