name: Keep Render App Alive

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping application URL
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://database-iupv.onrender.com
